allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
minimumReleaseAgeExclude:
  - framer-motion@12.39.0
  - motion-dom@12.39.0
  - motion-utils@12.39.0
  - motion@12.39.0
